name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

env:
  HUGO_services_googleAnalytics_ID: ${{ vars.HUGO_services_googleAnalytics_ID }}
  HUGO_ENV: "production"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Display the path
        shell: bash
        run: echo $HUGO_services_googleAnalytics_ID

      - name: Build
        if: github.repository == 'IT-Floss/IT-Floss.github.io'
        run: hugo --minify

      - name: Build on a fork repo
        if: github.repository != 'IT-Floss/IT-Floss.github.io'
        run: hugo --minify --baseURL https://${{ github.repository_owner }}.github.io/IT-Floss.github.io/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

